package br.com.centralit.testeselenium.suitedeteste;

import org.junit.runner.RunWith;
import org.junit.runners.Suite;
import org.junit.runners.Suite.SuiteClasses;

import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.CadastroTipoEventoServicoSelenium;
import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.CategoriaServicoSelenium;
import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.CategoriaSolucaoSelenium;
import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.CausaIncidenteSelenium;
import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.CondicaoOperacaoSelenium;
import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.ImportanciaNegocioSelenium;
import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.JustificativaSolicitacaoSelenium;
import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.LocalExecucaoServicosSelenium;
import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.PrioridadeSelenium;
import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.PrioridadeSolicitacaoSelenium;
import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.SituacaoServicoSelenium;
import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.TipoServicoSelenium;
import br.com.centralit.testeselenium.gerenciadecatalogosdeservico.TipoSolicitacaoServicoSelenium;

@RunWith(Suite.class)
@SuiteClasses({CadastroTipoEventoServicoSelenium.class, CategoriaServicoSelenium.class, CategoriaSolucaoSelenium.class, CausaIncidenteSelenium.class, CondicaoOperacaoSelenium.class,
	ImportanciaNegocioSelenium.class, JustificativaSolicitacaoSelenium.class, LocalExecucaoServicosSelenium.class, PrioridadeSelenium.class,  PrioridadeSolicitacaoSelenium.class,
	SituacaoServicoSelenium.class, TipoServicoSelenium.class, TipoSolicitacaoServicoSelenium.class})
public class SuiteDeTestesGerenciaDeCatalogoDeServico
{

}