-- Oracle

-- Início rodrigo.oliveira - 02/07/13

ALTER TABLE ATIVIDADESSERVICOCONTRATO MODIFY (PERIODO CHAR(1 CHAR));

ALTER TABLE ATIVIDADESSERVICOCONTRATO MODIFY (COMPLEXIDADE CHAR(1 CHAR));

-- Fim rodrigo.oliveira
