package br.com.centralit.citcorpore.teste;

import java.sql.Timestamp;
import java.util.Calendar;

import br.com.centralit.citcorpore.bean.SolicitacaoServicoDTO;
import br.com.centralit.citcorpore.bean.UsuarioDTO;
import br.com.centralit.citcorpore.negocio.SolicitacaoServicoService;
import br.com.citframework.excecao.ServiceException;
import br.com.citframework.service.ServiceLocator;
import br.com.citframework.util.UtilDatas;
import br.com.citframework.util.UtilTest;

public class SolicitacaoServicoTest {
	public String testCreateSolicitacao() {
		SolicitacaoServicoService solicitacaoServicoService;
		try {
			solicitacaoServicoService = (SolicitacaoServicoService) ServiceLocator.getInstance().getService(SolicitacaoServicoService.class, null);
			SolicitacaoServicoDTO solicitacaoServicoDTO = new SolicitacaoServicoDTO();
			UsuarioDTO usuarioDTO = new UsuarioDTO();
			usuarioDTO.setIdUsuario(430);
			solicitacaoServicoDTO.setUsuarioDto(usuarioDTO);
			Calendar cal = Calendar.getInstance();
			cal.set(2012, 05, 20, 9, 30);
			solicitacaoServicoDTO.setAcaoFluxo("A");
			solicitacaoServicoDTO.setAlterarSituacao("N");
			solicitacaoServicoDTO.setAtendimentoPresencial("S");
			solicitacaoServicoDTO.setAtrasoSLA(3);
			solicitacaoServicoDTO.setAtrasoSLAStr("S");
			solicitacaoServicoDTO.setCaracteristica("Teste");
			solicitacaoServicoDTO.setComplementoJustificativa("Teste");
			solicitacaoServicoDTO.setContrato("015");
			solicitacaoServicoDTO.setDataFim(UtilDatas.getDataAtual());
			solicitacaoServicoDTO.setDataInicio(new java.sql.Date(05, 02, 2012));
			solicitacaoServicoDTO.setDataHora(new Timestamp(cal.getTimeInMillis()));
			solicitacaoServicoDTO.setDataHoraCaptura(new Timestamp(cal.getTimeInMillis()));
			solicitacaoServicoDTO.setDataHoraFim(new Timestamp(cal.getTimeInMillis()));
			solicitacaoServicoDTO.setDataHoraInicio(new Timestamp(cal.getTimeInMillis()));
			solicitacaoServicoDTO.setDataHoraLimite(UtilDatas.getDataHoraAtual());
			solicitacaoServicoDTO.setDataHoraLimiteStr("10,10,2012");
			solicitacaoServicoDTO.setDataHoraLimiteToString("10,10,2012");
			solicitacaoServicoDTO.setDataHoraSolicitacao(UtilDatas.getDataHoraAtual());
			solicitacaoServicoDTO.setDataHoraSolicitacaoStr("05, 02, 2012");
			solicitacaoServicoDTO.setDataHoraSolicitacaoToString("05,02,2012");
			solicitacaoServicoDTO.setDataHoraReativacao(new Timestamp(cal.getTimeInMillis()));
			solicitacaoServicoDTO.setDataHoraSuspensao(UtilDatas.getDataHoraAtual());
			solicitacaoServicoDTO.setDemanda("3");
			solicitacaoServicoDTO.setDescricao("Testes");
			solicitacaoServicoDTO.setDescrSituacao("Teste");
			solicitacaoServicoDTO.setDetalhamentoCausa("Teste");
			solicitacaoServicoDTO.setEmailcontato("layanne.batista@centralit.com.br");
			solicitacaoServicoDTO.setEditar("N");
			solicitacaoServicoDTO.setEnviaEmailAcoes("S");
			solicitacaoServicoDTO.setEnviaEmailCriacao("S");
			solicitacaoServicoDTO.setEnviaEmailFinalizacao("S");
			solicitacaoServicoDTO.setEscalar("Teste");
			solicitacaoServicoDTO.setExibirCampoDescricao("S");
			solicitacaoServicoDTO.setFaseAtual("Teste");
			solicitacaoServicoDTO.setGrupoAtual("Central IT");
			solicitacaoServicoDTO.setGrupoNivel1("A");
			solicitacaoServicoDTO.setHouveMudanca("N");
			solicitacaoServicoDTO.setIdCalendario(2);
			solicitacaoServicoDTO.setIdGrupoNivel1(1);
			solicitacaoServicoDTO.setIdBaseConhecimento(8);
			solicitacaoServicoDTO.setIdCategoriaServico(739);
			solicitacaoServicoDTO.setIdCategoriaSolucao(12);
			solicitacaoServicoDTO.setIdCausaIncidente(11);
			solicitacaoServicoDTO.setIdContatoSolicitacaoServico(251);
			solicitacaoServicoDTO.setIdContrato(1);
			solicitacaoServicoDTO.setIdFaseAtual(1);
			solicitacaoServicoDTO.setIdGrupoAtual(1);
			solicitacaoServicoDTO.setIdGrupoDestino(2);
			solicitacaoServicoDTO.setIdJustificativa(9);
			solicitacaoServicoDTO.setIdLocalidade(1);
			solicitacaoServicoDTO.setIdOrigem(4);
			solicitacaoServicoDTO.setIdPrioridade(5);
			solicitacaoServicoDTO.setIdResponsavel(4);
			solicitacaoServicoDTO.setIdServico(605);
			solicitacaoServicoDTO.setIdServicoContrato(9);
			solicitacaoServicoDTO.setIdSolicitacaoPai(4);
			solicitacaoServicoDTO.setIdSolicitacaoServicoPesquisa(1);
			solicitacaoServicoDTO.setIdSolicitante(251);
			solicitacaoServicoDTO.setIdTarefa(4);
			solicitacaoServicoDTO.setIdTipoDemandaServico(1);
			solicitacaoServicoDTO.setIdTipoProblema(5);
			solicitacaoServicoDTO.setIdTipoServico(1);
			solicitacaoServicoDTO.setIdUnidade(1);
			solicitacaoServicoDTO.setIdUsuarioDestino(2);
			solicitacaoServicoDTO.setImpacto("A");
			solicitacaoServicoDTO.setItemConfiguracao("0");
			solicitacaoServicoDTO.setLinkPesquisaSatisfacao("Teste");
			solicitacaoServicoDTO.setMessageId("32");
			solicitacaoServicoDTO.setNomecontato("Layanne Cristine Batista");
			solicitacaoServicoDTO.setNomeCategoriaServico("Configurar");
			solicitacaoServicoDTO.setNomeServico("MONITORAMENTO.CLIENT.INSTALAR.");
			solicitacaoServicoDTO.setNomeSolicitante("Layanne Cristine Batista");
			solicitacaoServicoDTO.setNomeTarefa("Teste");
			solicitacaoServicoDTO.setNomeTipoDemandaServico("Teste");
			solicitacaoServicoDTO.setNomeTipoServico("Teste");
			solicitacaoServicoDTO.setNomeUnidadeResponsavel("Central IT");
			solicitacaoServicoDTO.setNomeUnidadeSolicitante("Central IT");
			solicitacaoServicoDTO.setNomeUsuario("Layanne Cristine Batista");
			solicitacaoServicoDTO.setNumeroRegistros(8);
			solicitacaoServicoDTO.setOrigem("OPERADOR");
			solicitacaoServicoDTO.setObservacao("Teste");
			solicitacaoServicoDTO.setOrdenacao("S");
			solicitacaoServicoDTO.setPrazoHH(7);
			solicitacaoServicoDTO.setPrazohhAnterior(9);
			solicitacaoServicoDTO.setPrazoMM(10);
			solicitacaoServicoDTO.setPrazommAnterior(6);
			solicitacaoServicoDTO.setPrioridade("B");
			solicitacaoServicoDTO.setQuantidade(9);
			solicitacaoServicoDTO.setRegistradoPor("Layanne");
			solicitacaoServicoDTO.setReclassificar("N");
			solicitacaoServicoDTO.setRegistroexecucao("Teste");
			solicitacaoServicoDTO.setResponsavel("Layanne Cristine Batista");
			solicitacaoServicoDTO.setResposta("Teste");
			solicitacaoServicoDTO.setSiglaGrupo("A");
			solicitacaoServicoDTO.setSeqReabertura(7);
			solicitacaoServicoDTO.setServico("MONITORAMENTO.CLIENT.INSTALAR.");
			solicitacaoServicoDTO.setServicoBusca("MONITORAMENTO.CLIENT.INSTALAR.");
			solicitacaoServicoDTO.setSituacao("EmAndamento");
			solicitacaoServicoDTO.setSlaACombinar("N");
			solicitacaoServicoDTO.setSolicitante("Layanne Cristine Batista");
			solicitacaoServicoDTO.setSolicitanteUnidade("Central IT");
			solicitacaoServicoDTO.setSolucaoTemporaria("N");
			solicitacaoServicoDTO.setTempoDecorridoMM(2);
			solicitacaoServicoDTO.setTelefonecontato("(062) 8221-8365");
			solicitacaoServicoDTO.setTarefa("N");
			solicitacaoServicoDTO.setTempoAtendimentoHH(8);
			solicitacaoServicoDTO.setTempoAtendimentoMM(10);
			solicitacaoServicoDTO.setTempoAtrasoHH(5);
			solicitacaoServicoDTO.setTempoAtrasoMM(7);
			solicitacaoServicoDTO.setTempoCapturaHH(2);
			solicitacaoServicoDTO.setTempoCapturaMM(4);
			solicitacaoServicoDTO.setTempoDecorridoHH(3);
			solicitacaoServicoDTO.setUrgencia("A");	
			solicitacaoServicoService.create(solicitacaoServicoDTO);
			return new UtilTest().testNotNull(solicitacaoServicoDTO.getIdSolicitacaoServico());
		} catch (ServiceException e) {
			e.printStackTrace();
			return e.getMessage();
		} catch (Exception e) {
			e.printStackTrace();
			return e.getMessage();
		}
	}
}