ALTER TABLE PROCESSAMENTOBATCH MODIFY (DESCRICAO varchar2(256)); 

--Início rodrigo.oliveira
DROP TABLE IMPACTO;

CREATE TABLE IMPACTO (
	IDIMPACTO NUMBER(10,0),
	NIVELIMPACTO VARCHAR2(100 CHAR),
	SIGLAIMPACTO CHAR(2 CHAR),
	PRIMARY KEY (IDIMPACTO)
);

INSERT INTO IMPACTO (IDIMPACTO, NIVELIMPACTO, SIGLAIMPACTO) VALUES ('1', 'Altíssimo', 'AL');
INSERT INTO IMPACTO (IDIMPACTO, NIVELIMPACTO, SIGLAIMPACTO) VALUES ('2', 'Alto', 'A');
INSERT INTO IMPACTO (IDIMPACTO, NIVELIMPACTO, SIGLAIMPACTO) VALUES ('3', 'Elevado', 'E');
INSERT INTO IMPACTO (IDIMPACTO, NIVELIMPACTO, SIGLAIMPACTO) VALUES ('4', 'Médio', 'M');
INSERT INTO IMPACTO (IDIMPACTO, NIVELIMPACTO, SIGLAIMPACTO) VALUES ('5', 'Baixo', 'B');

DROP TABLE URGENCIA;

CREATE TABLE URGENCIA (
	IDURGENCIA NUMBER(10,0),
	NIVELURGENCIA VARCHAR2(100 CHAR),
	SIGLAURGENCIA CHAR(2 CHAR),
	PRIMARY KEY (IDURGENCIA)
);

INSERT INTO URGENCIA (IDURGENCIA, NIVELURGENCIA, SIGLAURGENCIA) VALUES ('1', 'Crítica', 'C');
INSERT INTO URGENCIA (IDURGENCIA, NIVELURGENCIA, SIGLAURGENCIA) VALUES ('2', 'Alta', 'A');
INSERT INTO URGENCIA (IDURGENCIA, NIVELURGENCIA, SIGLAURGENCIA) VALUES ('3', 'Média', 'M');
INSERT INTO URGENCIA (IDURGENCIA, NIVELURGENCIA, SIGLAURGENCIA) VALUES ('4', 'Baixa', 'B');

DROP TABLE MATRIZPRIORIDADE;

CREATE TABLE MATRIZPRIORIDADE (
	IDMATRIZPRIORIDADE 	      NUMBER(10,0) NOT NULL,
	SIGLAIMPACTO 		      CHAR(2 CHAR) NOT NULL,
	SIGLAURGENCIA 		      CHAR(2 CHAR) NOT NULL,
	VALORPRIORIDADE 	      NUMBER(10,0) NOT NULL,
	IDCONTRATO 		          NUMBER(10,0) DEFAULT NULL,
	DELETED 		          CHAR(1 CHAR) DEFAULT NULL,
	PRIMARY KEY (IDMATRIZPRIORIDADE)
);

INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (1,'AL','B',2,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (2,'AL','M',2,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (3,'AL','A',1,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (4,'AL','C',1,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (5,'A','B',3,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (6,'A','M',2,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (7,'A','A',2,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (8,'A','C',1,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (9,'E','B',3,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (10,'E','M',3,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (11,'E','A',2,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (12,'E','C',2,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (13,'M','B',4,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (14,'M','M',3,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (15,'M','A',3,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (16,'M','C',2,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (17,'B','B',5,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (18,'B','M',4,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (19,'B','A',3,NULL,'');
INSERT INTO MATRIZPRIORIDADE (IDMATRIZPRIORIDADE,SIGLAIMPACTO,SIGLAURGENCIA,VALORPRIORIDADE,IDCONTRATO,DELETED) 
VALUES (20,'B','C',3,NULL,'');

CREATE TABLE tabfederacaodados (
   nometabela VARCHAR(255) NOT NULL,
   chavefinal VARCHAR(255) NOT NULL,
   chaveoriginal VARCHAR(255),
   origem VARCHAR(255),
   criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
   ultatualiz TIMESTAMP DEFAULT to_timestamp('01-JAN-70 00:00:00', 'dd-MON-yy hh24:mi:ss'),
   PRIMARY KEY(nometabela, chavefinal)
);

--Fim rodrigo.oliveira

