/*
-- Query: SELECT * FROM citsmart.templatesolicitacaoservico
LIMIT 0, 1000

-- Date: 2013-01-20 20:38
*/
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (1,'CriacaoRequisicaoProduto','Requisição Produto','br.com.centralit.citcorpore.bean.RequisicaoProdutoDTO','br.com.centralit.citcorpore.ajaxForms.RequisicaoProduto','br.com.centralit.citcorpore.negocio.RequisicaoProdutoServiceEjb','/pages/requisicaoProduto/requisicaoProduto.load','','N','N','N',600,'N','N','N','N');
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (2,'ValidacaoRequisicaoProduto','Validação Requisição Produto','br.com.centralit.citcorpore.bean.RequisicaoProdutoDTO','br.com.centralit.citcorpore.ajaxForms.ValidacaoRequisicaoProduto','br.com.centralit.citcorpore.negocio.RequisicaoProdutoServiceEjb','/pages/validacaoRequisicaoProduto/validacaoRequisicaoProduto.load','','N','N','N',650,'N','N','N','N');
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (3,'AutorizacaoCotacao','Autorização Cotação','br.com.centralit.citcorpore.bean.RequisicaoProdutoDTO','br.com.centralit.citcorpore.ajaxForms.AutorizacaoCotacao','br.com.centralit.citcorpore.negocio.RequisicaoProdutoServiceEjb','/pages/autorizacaoCotacao/autorizacaoCotacao.load','','N','N','N',650,'N','N','N','N');
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (4,'AcompanhamentoRequisicaoProduto','Acompanhamento Requisição Produto','br.com.centralit.citcorpore.bean.RequisicaoProdutoDTO','br.com.centralit.citcorpore.ajaxForms.AcompRequisicaoProduto','br.com.centralit.citcorpore.negocio.RequisicaoProdutoServiceEjb','/pages/acompRequisicaoProduto/acompRequisicaoProduto.load','','N','S','N',650,'N','N','N','N');
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (5,'AprovacaoCotacao','Aprovação da Cotação','br.com.centralit.citcorpore.bean.RequisicaoProdutoDTO','br.com.centralit.citcorpore.ajaxForms.AprovacaoCotacao','br.com.centralit.citcorpore.negocio.RequisicaoProdutoServiceEjb','/pages/aprovacaoCotacao/aprovacaoCotacao.load','','N','N','N',650,'N','N','N','N');
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (7,'AlteracaoRequisicaoProduto','Alteração da Requisição','br.com.centralit.citcorpore.bean.RequisicaoProdutoDTO','br.com.centralit.citcorpore.ajaxForms.RequisicaoProduto','br.com.centralit.citcorpore.negocio.RequisicaoProdutoServiceEjb','/pages/requisicaoProduto/requisicaoProduto.load',NULL,'N','S','N',650,'N','N','N','N');
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (8,'InspecaoEntregaItem','Inspeção de entrega da requisiçao','br.com.centralit.citcorpore.bean.RequisicaoProdutoDTO','br.com.centralit.citcorpore.ajaxForms.InspecaoEntregaItem','br.com.centralit.citcorpore.negocio.RequisicaoProdutoServiceEjb','/pages/inspecaoEntregaItem/inspecaoEntregaItem.load','','N','N','N',650,'N','N','N','N');
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (9,'AcionamentoGarantia','Acionamento da garantia','br.com.centralit.citcorpore.bean.RequisicaoProdutoDTO','br.com.centralit.citcorpore.ajaxForms.AcionamentoGarantia','br.com.centralit.citcorpore.negocio.RequisicaoProdutoServiceEjb','/pages/acionamentoGarantia/acionamentoGarantia.load','','N','N','N',650,'N','N','N','N');
