INSERT INTO `bpm_tipofluxo` (`idtipofluxo`,`nomefluxo`,`descricao`,`nomeclassefluxo`) VALUES ($ID_TIPO_FLUXO,'RequisicaoMudanca','Requisição de Mudança','br.com.centralit.citcorpore.bpm.negocio.RequisicaoMudanca');

INSERT INTO `bpm_fluxo` (`idfluxo`,`versao`,`idtipofluxo`,`variaveis`,`conteudoxml`,`datainicio`,`datafim`) VALUES ($ID_FLUXO,'3.0',$ID_TIPO_FLUXO,'requisicaoMudanca;requisicaoMudanca.status;requisicaoMudanca.nomeGrupoAtual;requisicaoMudanca.grupoNivel1',NULL,'2013-01-09',NULL);

INSERT INTO `bpm_elementofluxo` (`idelemento`,`idfluxo`,`tipoelemento`,`subtipo`,`nome`,`documentacao`,`tipointeracao`,`url`,`visao`,`grupos`,`usuarios`,`acaoentrada`,`acaosaida`,`script`,`textoemail`,`nomefluxoencadeado`,`posx`,`posy`,`altura`,`largura`,`modeloemail`,`template`,`intervalo`,`condicaodisparo`,`multiplasinstancias`) VALUES (184,$ID_FLUXO,'Inicio','','','','','','','','','','','','','',94,56,32,32,'','',NULL,'','');
INSERT INTO `bpm_elementofluxo` (`idelemento`,`idfluxo`,`tipoelemento`,`subtipo`,`nome`,`documentacao`,`tipointeracao`,`url`,`visao`,`grupos`,`usuarios`,`acaoentrada`,`acaosaida`,`script`,`textoemail`,`nomefluxoencadeado`,`posx`,`posy`,`altura`,`largura`,`modeloemail`,`template`,`intervalo`,`condicaodisparo`,`multiplasinstancias`) VALUES (185,$ID_FLUXO,'Tarefa','','Avaliar','Avaliar','U','pages/requisicaoMudanca/requisicaoMudanca.load?alterarSituacao=N&fase=Execucao&fase=Avaliacao','','#{requisicaoMudanca.nomeGrupoAtual}','','','','','','',703,168,65,140,'','',NULL,'','');
INSERT INTO `bpm_elementofluxo` (`idelemento`,`idfluxo`,`tipoelemento`,`subtipo`,`nome`,`documentacao`,`tipointeracao`,`url`,`visao`,`grupos`,`usuarios`,`acaoentrada`,`acaosaida`,`script`,`textoemail`,`nomefluxoencadeado`,`posx`,`posy`,`altura`,`largura`,`modeloemail`,`template`,`intervalo`,`condicaodisparo`,`multiplasinstancias`) VALUES (186,$ID_FLUXO,'Tarefa','','Aprovar','Aprovar','U','/pages/requisicaoMudanca/requisicaoMudanca.load?alterarSituacao=N&fase=Aprovacao','','#{requisicaoMudanca.nomeGrupoAtual}','','','','','','',40,168,65,140,'','',NULL,'','');
INSERT INTO `bpm_elementofluxo` (`idelemento`,`idfluxo`,`tipoelemento`,`subtipo`,`nome`,`documentacao`,`tipointeracao`,`url`,`visao`,`grupos`,`usuarios`,`acaoentrada`,`acaosaida`,`script`,`textoemail`,`nomefluxoencadeado`,`posx`,`posy`,`altura`,`largura`,`modeloemail`,`template`,`intervalo`,`condicaodisparo`,`multiplasinstancias`) VALUES (187,$ID_FLUXO,'Tarefa','','Planejar','Planejar','U','pages/requisicaoMudanca/requisicaoMudanca.load?alterarSituacao=N&fase=Planejamento','','#{requisicaoMudanca.nomeGrupoAtual}','','','','','','',255,168,65,140,'','',NULL,'','');
INSERT INTO `bpm_elementofluxo` (`idelemento`,`idfluxo`,`tipoelemento`,`subtipo`,`nome`,`documentacao`,`tipointeracao`,`url`,`visao`,`grupos`,`usuarios`,`acaoentrada`,`acaosaida`,`script`,`textoemail`,`nomefluxoencadeado`,`posx`,`posy`,`altura`,`largura`,`modeloemail`,`template`,`intervalo`,`condicaodisparo`,`multiplasinstancias`) VALUES (188,$ID_FLUXO,'Tarefa','','Executar','Executar','U','pages/requisicaoMudanca/requisicaoMudanca.load?alterarSituacao=N&fase=Execucao','','#{requisicaoMudanca.nomeGrupoAtual}','','','','','','',482,168,65,140,'','',NULL,'','');
INSERT INTO `bpm_elementofluxo` (`idelemento`,`idfluxo`,`tipoelemento`,`subtipo`,`nome`,`documentacao`,`tipointeracao`,`url`,`visao`,`grupos`,`usuarios`,`acaoentrada`,`acaosaida`,`script`,`textoemail`,`nomefluxoencadeado`,`posx`,`posy`,`altura`,`largura`,`modeloemail`,`template`,`intervalo`,`condicaodisparo`,`multiplasinstancias`) VALUES (189,$ID_FLUXO,'Finalizacao','','','','','','','','','','','','','',918,184,32,32,'','',NULL,'','');

INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (184,186,$ID_FLUXO,NULL,NULL,'',2,0,110,128,'N',NULL);
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (185,189,$ID_FLUXO,NULL,NULL,'',1,3,880.5,200.$ID_FLUXO,'N',NULL);
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (186,187,$ID_FLUXO,NULL,NULL,'',1,3,217.5,200.5,'N',NULL);
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (187,188,$ID_FLUXO,NULL,NULL,'',1,3,438.5,200.5,'N',NULL);
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (188,185,$ID_FLUXO,NULL,NULL,'',1,3,662.5,200.5,'N',NULL);

