/*
-- Query: SELECT * FROM citsmart_novo_homologacao.bpm_sequenciafluxo where idfluxo = 36
LIMIT 0, 1000

-- Date: 2013-02-27 09:13
*/
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (352,364,36,NULL,NULL,'!#{solicitacaoServico}.atendida();',1,3,59.5,38,'N','não atendida');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (353,370,36,NULL,NULL,'',2,0,206,87,'N','');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (354,355,36,NULL,NULL,'!#{execucaoFluxo}.requisicaoRejeitada();',2,0,599,186.5,'N','não rejeitada');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (354,371,36,NULL,NULL,'',0,2,599,77,'N','');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (355,360,36,NULL,NULL,'#{solicitacaoServico}.finalizada();',2,2,598,391,'S','finalizada');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (356,360,36,NULL,NULL,'#{solicitacaoServico}.finalizada();',2,3,206,346,'S','finalizada');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (356,364,36,NULL,NULL,'',3,2,97,269,'S','');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (360,373,36,NULL,NULL,'',1,3,909,346.75,'N','');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (361,372,36,NULL,NULL,'',1,3,734,242.5,'N','');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (362,356,36,NULL,NULL,'',2,0,206.75,218.5,'N','');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (363,356,36,NULL,NULL,'',3,1,290,39,'S','');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (364,353,36,NULL,NULL,'',1,3,123.5,37.75,'N','');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (365,354,36,NULL,NULL,'',1,3,512,126.25,'N','');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (366,357,36,NULL,NULL,'',1,3,855,54.75,'N','');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (367,358,36,NULL,NULL,'',1,3,890,135.75,'N','');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (368,359,36,NULL,NULL,'',1,3,892,276.75,'N',NULL);
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (369,355,36,NULL,NULL,'!#{execucaoFluxo}.exigeAutorizacao();',2,3,434,199,'S','não exige autorização');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (369,361,36,NULL,NULL,'!#{execucaoFluxo}.exigeAutorizacao();',2,2,365,337,'S','não exige autorização');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (369,365,36,NULL,NULL,'#{execucaoFluxo}.exigeAutorizacao();',1,3,425.5,126,'N',' exige autorização');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (370,362,36,NULL,NULL,'#{execucaoFluxo}.requisicaoRejeitada();',2,0,206.25,162,'N','rejeitada');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (370,369,36,NULL,NULL,'!#{execucaoFluxo}.requisicaoRejeitada();',1,3,286,125.5,'N','não rejeitada');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (371,361,36,NULL,NULL,'!#{execucaoFluxo}.requisicaoRejeitada();',1,0,684,39,'S','não rejeitada');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (371,363,36,NULL,NULL,'#{execucaoFluxo}.requisicaoRejeitada();',3,1,483,39,'N','rejeitada');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (372,360,36,NULL,NULL,'#{execucaoFluxo}.entregaFinalizada();',2,0,788,255,'N','entrega finalizada');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (372,366,36,NULL,NULL,'#{execucaoFluxo}.existeAprovacaoPendente();',0,2,787.75,110,'N','aprovação pendente');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (372,367,36,NULL,NULL,'#{execucaoFluxo}.existeEntregaPendenteInspecao();',1,2,856,176,'S','inspeção entrega pendente');
INSERT INTO `bpm_sequenciafluxo` (`idelementoorigem`,`idelementodestino`,`idfluxo`,`nomeclasseorigem`,`nomeclassedestino`,`condicao`,`idconexaoorigem`,`idconexaodestino`,`bordax`,`borday`,`posicaoalterada`,`nome`) VALUES (372,368,36,NULL,NULL,'#{execucaoFluxo}.existeEntregaNaoAprovada();',1,0,858,224,'S','entrega não aprovada');
