/*
-- Query: SELECT * FROM citsmart.templatesolicitacaoservico where idtemplate >= 10
LIMIT 0, 1000

-- Date: 2013-04-24 10:47
*/
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (116,'SolicitacaoCargo','Solicitação de Cargo','br.com.centralit.citcorpore.bean.DescricaoCargoDTO','br.com.centralit.citcorpore.ajaxForms.SolicitacaoCargo','br.com.centralit.citcorpore.negocio.DescricaoCargoServiceEjb','/pages/solicitacaoCargo/solicitacaoCargo.load','','N','S','N',800,'S','N','N','N');
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (117,'AnaliseSolicitacaoCargo','Análise Solicitação de Cargo','br.com.centralit.citcorpore.bean.DescricaoCargoDTO','br.com.centralit.citcorpore.ajaxForms.AnaliseSolicitacaoCargo','br.com.centralit.citcorpore.negocio.DescricaoCargoServiceEjb','/pages/analiseSolicitacaoCargo/analiseSolicitacaoCargo.load',NULL,'N','S','N',800,'S','N','N','N');
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (112,'RequisicaoPessoal','Requisição Pessoal','br.com.centralit.citcorpore.bean.RequisicaoPessoalDTO','br.com.centralit.citcorpore.ajaxForms.RequisicaoPessoal','br.com.centralit.citcorpore.negocio.RequisicaoPessoalServiceEjb','/pages/requisicaoPessoal/requisicaoPessoal.load',NULL,'N','S','N',1000,'S','N','N','N');
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (113,'AnaliseRequisicaoPessoal','Análise Requisição Pessoal','br.com.centralit.citcorpore.bean.RequisicaoPessoalDTO','br.com.centralit.citcorpore.ajaxForms.AnaliseRequisicaoPessoal','br.com.centralit.citcorpore.negocio.RequisicaoPessoalServiceEjb','/pages/analiseRequisicaoPessoal/analiseRequisicaoPessoal.load',NULL,'N','S','N',1000,'S','N','N','N');
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (114,'TriagemRequisicaoPessoal','Triagem Requisição Pessoal','br.com.centralit.citcorpore.bean.RequisicaoPessoalDTO','br.com.centralit.citcorpore.ajaxForms.TriagemRequisicaoPessoal','br.com.centralit.citcorpore.negocio.RequisicaoPessoalServiceEjb','/pages/triagemRequisicaoPessoal/triagemRequisicaoPessoal.load',NULL,'N','S','N',650,'S','N','N','N');
INSERT INTO `templatesolicitacaoservico` (`idtemplate`,`identificacao`,`nometemplate`,`nomeclassedto`,`nomeclasseaction`,`nomeclasseservico`,`urlrecuperacao`,`scriptaposrecuperacao`,`habilitadirecionamento`,`habilitasituacao`,`habilitasolucao`,`alturadiv`,`habilitaurgenciaimpacto`,`habilitanotificacaoemail`,`habilitamudanca`,`habilitaproblema`) VALUES (115,'EntrevistaRequisicaoPessoal','Entrevista Requisicao Pessoal','br.com.centralit.citcorpore.bean.RequisicaoPessoalDTO','br.com.centralit.citcorpore.ajaxForms.EntrevistaRequisicaoPessoal','br.com.centralit.citcorpore.negocio.RequisicaoPessoalServiceEjb','/pages/entrevistaRequisicaoPessoal/entrevistaRequisicaoPessoal.load',NULL,'N','S','N',650,'S','N','N','N');
